language: c

sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.2

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto --name alexis-collection-lens --link $TRAVIS_BUILD_DIR

before_script:

script:
  - raco test -p alexis-collection-lens

after_script:
